---
execute:
  cache: true

project:
  type: book
  output-dir: _book

book:
  title: "Pay Ratio Disclosure"
  output-file: "template-project"
  author: "Victor Schauer"
  date: "2024-03-28"
  repo-url: https://trr266.github.io/quarto-template-data-website-2/
  repo-actions: [issue, edit]
  repo-subdir: docs
  chapters:
    - index.qmd
    - data-collection.qmd
    - data-preview.qmd

format:
  html:
    theme: cosmo
    fig-format: retina
    code-fold: false