---
execute:
  cache: true

project:
  type: book
  output-dir: _book

book:
  title: "PR App"
  output-file: "template-project"
  author: "Victor Schauer"
  date: "2024-04-15"
  repo-url: https://github.com/trr266/quarto-template-data-website-2
  repo-actions: [issue, edit]
  repo-subdir: docs
  chapters:
    - pr-viz.qmd
    - background.qmd
    - data-collection-process.qmd
    - data-set.qmd

format:
  html:
    theme: cosmo
    fig-format: retina
    code-fold: false
